<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1515;CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DesktopAccountingApi.QuickBooksDesktop/DesktopAccountingApi.QuickBooksDesktop.csproj" />
  </ItemGroup>
</Project>
